window.Metamaps = window.Metamaps || {}

import './Constants'

import './Account'
import './Admin'
import './AutoLayout'
import './Backbone'
import './Control'
import './Create'
import './Debug'
import './Filter'
import './GlobalUI'
import './Import'
import './JIT'
import './Listeners'
import './Map'
import './Mapper'
import './Mobile'
import './Organize'
import './PasteInput'
import './Realtime'
import './Router'
import './Synapse'
import './SynapseCard'
import './Topic'
import './TopicCard'
import './Util'
import './Views'
import './Visualize'
import './ReactComponents'

export default window.Metamaps
