#%RAML 1.0
---
title: Metamaps
version: 2.0
baseUri: https://metamaps.cc/api/v2
mediaType: application/json
protocols: [ HTTPS ]
documentation:
  - title: Getting Started
    content: !include pages/getting-started.md
  - title: Endpoints
    content: ""

securitySchemes:
  oauth_2_0: !include securitySchemes/oauth_2_0.raml
securedBy: [ oauth_2_0 ]

traits:
  pageable: !include traits/pageable.raml
  embeddable: !include traits/embeddable.raml
  orderable: !include traits/orderable.raml
  searchable: !include traits/searchable.raml

schemas:
  map: !include schemas/_map.json
  mapping: !include schemas/_mapping.json
  metacode: !include schemas/_metacode.json
  synapse: !include schemas/_synapse.json
  token: !include schemas/_token.json
  topic: !include schemas/_topic.json
  user: !include schemas/_user.json

#resourceTypes:
#  base: !include resourceTypes/base.raml
#  item: !include resourceTypes/item.raml
#  collection: !include resourceTypes/collection.raml

/maps: !include apis/maps.raml
/mappings: !include apis/mappings.raml
/metacodes: !include apis/metacodes.raml
/synapses: !include apis/synapses.raml
/tokens: !include apis/tokens.raml
/topics: !include apis/topics.raml
/users: !include apis/users.raml
