get?:
  responses:
    400:
      description: Invalid request or params
      body:
        application/json:
          schema: error
put?:
  responses:
    400:
      description: Invalid request or params
      body:
        application/json:
          schema: error
patch?:
  responses:
    400:
      description: Invalid request or params
      body:
        application/json:
          schema: error
post?:
  responses:
    400:
      description: Invalid request or params
      body:
        application/json:
          schema: error
delete?:
  responses:
    400:
      description: Invalid request or params
      body:
        application/json:
          schema: error
