#type: collection
get:
  description: |
    A list of the current user's tokens.
  is: [ searchable: { searchFields: description }, pageable, orderable ]
  securedBy: [ token, oauth_2_0, cookie ]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/tokens.json
post:
  securedBy: [ token, oauth_2_0, cookie ]
  body:
    application/json:
      properties:
        description:
          description: short string describing this token
          required: false
  responses:
    201:
      body:
        application/json:
          example: !include ../examples/token.json
/{id}:
  #type: item
  securedBy: [ token, oauth_2_0, cookie ]
  delete:
    responses:
      204:
        description: No content
