#type: collection
get:
  is: [ searchable: { searchFields: "name" }, orderable, pageable ]
  securedBy: [ null, token, oauth_2_0, cookie ]
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/users.json
/{id}:
  #type: item
  securedBy: [ null, token, oauth_2_0, cookie ]
  get:
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/user.json
/current:
  #type: item
  get:
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/current_user.json
