queryParameters:
  embed:
    description: |
      Comma-separated list of columns to embed. Each embedded column will be returned instead of the corresponding <code>field_id</code> or <code>field_ids</code> column. For instance, <code>?embed=user</code> would remove the <code>user_id</code> integer field from a response and replace it with a <code>user</code> object field. 
      
      Possible embeddable fields are: <pre><< embedFields >></pre>
    required: false
    type: string
