description: |
  OAuth 2.0 implementation
type: OAuth 2.0
settings:
  authorizationUri: https://metamaps.cc/api/v2/oauth/authorize
  accessTokenUri: https://metamaps.cc/api/v2/oauth/token
  authorizationGrants: [ authorization_code, client_credentials ]
