description: !include ../pages/oauth_2_0_tutorial.md
type: OAuth 2.0
settings:
  authorizationUri: https://metamaps.cc/api/v2/oauth/authorize
  accessTokenUri: https://metamaps.cc/api/v2/oauth/token
  authorizationGrants: [ authorization_code, client_credentials ]
