export const OPEN_CHAT = 'OPEN_CHAT'
export const CLOSE_CHAT = 'CLOSE_CHAT'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'

export const OPEN_NOTIFICATIONS = 'OPEN_NOTIFICATIONS'
export const CLOSE_NOTIFICATIONS = 'CLOSE_NOTIFICATIONS'
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ'
export const MARK_NOTIFICATION_UNREAD = 'MARK_NOTIFICATION_UNREAD'

export const OPEN_ACCOUNT_MENU = 'OPEN_ACCOUNT_MENU'
export const CLOSE_ACCOUNT_MENU = 'CLOSE_ACCOUNT_MENU'
export const STAR_MAP = 'STAR_MAP'
export const UNSTAR_MAP = 'UNSTAR_MAP'
export const FOLLOW_MAP = 'FOLLOW_MAP'
export const UNFOLLOW_MAP = 'UNFOLLOW_MAP'
export const FOLLOW_TOPIC = 'FOLLOW_TOPIC'
export const UNFOLLOW_TOPIC = 'UNFOLLOW_TOPIC'

export const PIN_CREATE_TOPIC = 'PIN_CREATE_TOPIC_OPEN'
export const UNPIN_CREATE_TOPIC = 'UNPIN_CREATE_TOPIC'
export const OPEN_CREATE_TOPIC = 'OPEN_CREATE_TOPIC'
export const CLOSE_CREATE_TOPIC = 'CLOSE_CREATE_TOPIC'
export const CREATE_TOPIC = 'CREATE_TOPIC'
export const UPDATE_TOPIC = 'UPDATE_TOPIC'

export const OPEN_CREATE_SYNAPSE = 'OPEN_CREATE_SYNAPSE'
export const CLOSE_CREATE_SYNAPSE = 'CLOSE_CREATE_SYNAPSE'
export const CREATE_SYNAPSE = 'CREATE_SYNAPSE'
export const UPDATE_SYNAPSE = 'UPDATE_SYNAPSE'

export const UPDATE_METACODE_SET = 'UPDATE_METACODE_SET'
export const MAKE_SELECTION = 'MAKE_SELECTION'
export const HIDE_SELECTED = 'HIDE_SELECTED'
export const REMOVE_SELECTED = 'REMOVE_SELECTED'
export const DELETE_SELECTED = 'DELETE_SELECTED'
export const CHANGE_PERMISSION_SELECTED = 'CHANGE_PERMISSION_SELECTED'
export const CHANGE_METACODE_SELECTED = 'CHANGE_METACODE_SELECTED'

export const OPEN_TOPIC_CARD = 'OPEN_TOPIC_CARD'
export const CLOSE_TOPIC_CARD = 'CLOSE_TOPIC_CARD'

export const OPEN_SYNAPSE_CARD = 'OPEN_SYNAPSE_CARD'
export const CLOSE_SYNAPSE_CARD = 'CLOSE_SYNAPSE_CARD'

export const OPEN_METACODE_SET_SELECT = 'OPEN_METACODE_SET_SELECT'
export const CLOSE_METACODE_SET_SELECT = 'CLOSE_METACODE_SET_SELECT'
export const SELECT_METACODE_SET = 'SELECT_METACODE_SET'

export const OPEN_MAP_INFO_BOX = 'OPEN_MAP_INFO_BOX'
export const CLOSE_MAP_INFO_BOX = 'CLOSE_MAP_INFO_BOX'
export const UPDATE_MAP = 'UPDATE_MAP'

export const OPEN_HELP = 'OPEN_HELP'
export const CLOSE_HELP = 'CLOSE_HELP'

export const MAP_CENTER_VIEW = 'MAP_CENTER_VIEW'
export const MAP_ZOOM_IN = 'MAP_ZOOM_IN'
export const MAP_ZOOM_OUT = 'MAP_ZOOM_OUT'

export const MAP_DISABLE_SOUND = 'MAP_DISABLE_SOUND'
export const MAP_ENABLE_SOUND = 'MAP_ENABLE_SOUND'

export const MAP_DISABLE_CURSOR = 'MAP_DISABLE_CURSOR'
export const MAP_ENABLE_CURSOR = 'MAP_ENABLE_CURSOR'

export const MAP_HIDE_VIDEOS = 'MAP_HIDE_VIDEOS'
export const MAP_UNHIDE_VIDEOS = 'MAP_UNHIDE_VIDEOS'

export const OPEN_IMPORT_DIALOGUE = 'OPEN_IMPORT_DIALOGUE'
export const CLOSE_IMPORT_DIALOGUE = 'CLOSE_IMPORT_DIALOGUE'

export const OPEN_FILTERS = 'OPEN_FILTERS'
export const CLOSE_FILTERS = 'CLOSE_FILTERS'

export const FILTER_ALL_PEOPLE = 'FILTER_ALL_PEOPLE'
export const FILTER_NO_PEOPLE = 'FILTER_NO_PEOPLE'
export const FILTER_HIDE_PERSON = 'FILTER_HIDE_PERSON'
export const FILTER_SHOW_PERSON = 'FILTER_SHOW_PERSON'

export const FILTER_ALL_METACODES = 'FILTER_ALL_METACODES'
export const FILTER_NO_METACODES = 'FILTER_NO_METACODES'
export const FILTER_HIDE_METACODE = 'FILTER_HIDE_METACODE'
export const FILTER_SHOW_METACODE = 'FILTER_SHOW_METACODE'

export const FILTER_ALL_SYNAPSES = 'FILTER_ALL_SYNAPSES'
export const FILTER_NO_SYNAPSES = 'FILTER_NO_SYNAPSES'
export const FILTER_HIDE_SYNAPSE = 'FILTER_HIDE_SYNAPSE'
export const FILTER_SHOW_SYNAPSE = 'FILTER_SHOW_SYNAPSE'

export const OPEN_FORK_MAP = 'OPEN_FORK_MAP'
export const CLOSE_FORK_MAP = 'CLOSE_FORK_MAP'

export const RIGHT_CLICK_ON_NODE = 'RIGHT_CLICK_ON_NODE'
export const RIGHT_CLICK_ON_EDGE = 'RIGHT_CLICK_ON_EDGE'

export const MAP_REQUEST_ACCESS = 'MAP_REQUEST_ACCESS'
