#!/usr/bin/env ruby.exe
# frozen_string_literal: true

APP_PATH = File.expand_path('../../config/application', __FILE__)
require File.expand_path('../../config/boot', __FILE__)
require 'rails/commands'
